export const googleFonts = [
    "Amatic SC",
    "Anton",
    "Arimo",
    "Baloo 2",
    "Bebas Neue",
    "Bitter",
    "Cabin",
    "Catamaran",
    "Comfortaa",
    "Cormorant Garamond",
    "Dosis",
    "DM Sans",
    "Droid Sans",
    "Exo 2",
    "Fira Sans",
    "Fredoka One",
    "Heebo",
    "Hind",
    "Inconsolata",
    "Inter",
    "Josefin Sans",
    "Karla",
    "Lato",
    "Libre Baskerville",
    "Lora",
    "Merriweather",
    "Merriweather Sans",
    "Muli",
    "Mukta",
    "Noto Sans",
    "Nunito",
    "Open Sans",
    "Oswald",
    "Overpass",
    "Pacifico",
    "Playfair Display",
    "Poppins",
    "PT Sans",
    "Quicksand",
    "Raleway",
    "Roboto",
    "Roboto Condensed",
    "Rubik",
    "Righteous",
    "Satisfy",
    "Signika",
    "Source Sans Pro",
    "Teko",
    "Ubuntu",
    "Varela Round",
    "Work Sans",
    "Zilla Slab"
  ];